name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        
    steps:
    - uses: actions/checkout@v3

    - name: Build with Go Release
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}
        goarch: ${{ matrix.arch }}
        binary_name: ehost
        build_command: go build -o ehost
        extra_files: LICENSE README.md
        release_tag: pr-${{ github.event.pull_request.number }}
        md5sum: false
        upload_assets: false
