name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: ehost
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: true

      # Trigger CI workflow when a new release is created
      - name: Trigger CI
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-created
          client-payload: '{"ref": "${{ steps.release.outputs.tag_name }}", "merged": true}'